language: node_js

node_js: "10.15.1"

install: npm install

scripts: npm test

before_script :
  - psql -c 'CREATE DATABASE property_test;' -U postgres
  - psql -c 'CREATE USER alfredchada WITH PASSWORD "jpcjdclock";' -U postgres

after_script :
  - npm install coveralls && npm run coverage
